name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build Golang project
        run: |
          go mod tidy
          go build -o my-vue-app.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-vue-app
          path: my-vue-app.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-vue-app
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: my-vue-app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
