name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Update Go Modules
        run: |
          go get github.com/webview/webview_go@latest
          go mod tidy

      - name: Build Golang project
        run: |
          GOOS=windows GOARCH=amd64 go build -o my-vue-app.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-vue-app
          path: my-vue-app.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-vue-app
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: my-vue-app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
